pip install setuptools
pip install wheel
pip install streamlit
pip install yfinance
pip install numpy
pip install pandas
pip install pandas-ta
pip install scikit-learn
pip install tensorflow
pip install plotly